# Generated by Django 4.0.3 on 2022-03-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='def', max_length=10000),
            preserve_default=False,
        ),
    ]
