# Generated by Django 4.0.3 on 2022-03-14 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('postalCode', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('IN', 'INDIAN'), ('IT', 'ITALIAN'), ('AM', 'AMERICAN'), ('PI', 'PIZZA'), ('CH', 'CHINESE')], max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('short_description', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('like_count', models.PositiveBigIntegerField()),
                ('dislike_count', models.PositiveBigIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
