# Generated by Django 4.0.3 on 2022-03-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_blogpost_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_code', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
