# Generated by Django 4.0.3 on 2022-03-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurantpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='like_count',
        ),
    ]
