# Generated by Django 4.0.3 on 2022-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_blogpost_dislike_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='hello', max_length=10000),
            preserve_default=False,
        ),
    ]
